<?php
include '../../includes/config.php';
include '../../includes/auth.php';

// Require admin authentication for API access
if (!isAdminLoggedIn()) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}

try {
    // Get export format
    $format = $_GET['format'] ?? 'csv';
    $category = $_GET['category'] ?? '';
    
    // Get channels
    $query = "SELECT * FROM channels WHERE 1=1";
    $params = [];
    
    if ($category) {
        $query .= " AND category = ?";
        $params[] = $category;
    }
    
    $query .= " ORDER BY category, name";
    $stmt = $pdo->prepare($query);
    $stmt->execute($params);
    $channels = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    if ($format === 'csv') {
        // Export as CSV
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename=channels_export_' . date('Y-m-d') . '.csv');
        
        $output = fopen('php://output', 'w');
        
        // CSV header
        fputcsv($output, [
            'Name', 'Category', 'Stream URL', 'Logo URL', 'TVG ID', 
            'DRM Type', 'License Key', 'License URL', 'Views', 'Active'
        ]);
        
        // CSV data
        foreach ($channels as $channel) {
            fputcsv($output, [
                $channel['name'],
                $channel['category'],
                $channel['stream_url'],
                $channel['logo_url'],
                $channel['tvg_id'],
                $channel['drm_type'],
                $channel['license_key'],
                $channel['license_url'],
                $channel['views'],
                $channel['is_active'] ? 'Yes' : 'No'
            ]);
        }
        
        fclose($output);
        
    } elseif ($format === 'json') {
        // Export as JSON
        header('Content-Type: application/json; charset=utf-8');
        header('Content-Disposition: attachment; filename=channels_export_' . date('Y-m-d') . '.json');
        
        echo json_encode($channels, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        
    } elseif ($format === 'm3u') {
        // Export as M3U
        header('Content-Type: application/vnd.apple.mpegurl; charset=utf-8');
        header('Content-Disposition: attachment; filename=channels_export_' . date('Y-m-d') . '.m3u');
        
        echo "#EXTM3U\n";
        echo "# Generated by IPTV Admin Panel on " . date('Y-m-d H:i:s') . "\n";
        echo "# Total channels: " . count($channels) . "\n\n";
        
        foreach ($channels as $channel) {
            // EXTINF line
            $extinf = "#EXTINF:-1";
            
            if ($channel['tvg_id']) {
                $extinf .= " tvg-id=\"{$channel['tvg_id']}\"";
            }
            
            if ($channel['logo_url']) {
                $extinf .= " tvg-logo=\"{$channel['logo_url']}\"";
            }
            
            if ($channel['category']) {
                $extinf .= " group-title=\"{$channel['category']}\"";
            }
            
            $extinf .= "," . $channel['name'];
            
            // DRM properties
            if ($channel['drm_type']) {
                echo "#KODIPROP:inputstream.adaptive.license_type={$channel['drm_type']}\n";
            }
            
            if ($channel['license_key']) {
                echo "#KODIPROP:inputstream.adaptive.license_key={$channel['license_key']}\n";
            }
            
            if ($channel['license_url']) {
                echo "#KODIPROP:inputstream.adaptive.license_url={$channel['license_url']}\n";
            }
            
            echo $extinf . "\n";
            echo $channel['stream_url'] . "\n\n";
        }
        
    } else {
        throw new Exception('Unsupported export format');
    }
    
} catch (Exception $e) {
    http_response_code(400);
    header('Content-Type: application/json');
    echo json_encode(['error' => $e->getMessage()]);
}
?>